# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from your local project to the container
COPY . .

# Build the React app for production
RUN npm run build

# Expose a port for the application (usually 80 for HTTP)
EXPOSE 80

# Start the React application 
CMD ["npm","run","dev"]
